Source/Controllers/TutorialController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ezyd.Controllers
{
    [HandleError]
    public class TutorialController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult friendlistTutorial()
        {
            return View();
        }

        public ActionResult createNewTransaction()
        {
            return View();
        }

        public ActionResult accAndExeTransactionTutorial()
        {
            return View();
        }

        public ActionResult HowItWorksCartoon()
        {
            return View();
        }

        public ActionResult whyUErrorToMeCartooon()
        {
            return View();
        }

        public ActionResult suspendOptimization()
        {
            return View();
        }
    }
}

Source/Views/Tutorial/HowItWorksCartoon.cshtml
@{
    ViewBag.Title = "HowItWorksCartoon";
}

<h2>@this.LclRes("Go back to") @Html.ActionLink("tutorial menu", "index", "tutorial")</h2>

<h4>@this.LclRes("String1")</h4>
<img src="@Url.Content(this.LclRes("Img1"))" alt="how it works cartoon"/>
<br />
<img src="@Url.Content(this.LclRes("Img2"))" alt="how it works cartoon"/>
<br />
<img src="@Url.Content(this.LclRes("Img3"))" alt="how it works cartoon"/>
<br />
<img src="@Url.Content(this.LclRes("Img4"))" alt="how it works cartoon"/>
<br />
<img src="@Url.Content(this.LclRes("Img5"))" alt="how it works cartoon"/>
<br />

Source/Views/Tutorial/Index.cshtml
<h3>@this.LclRes("String1")</h3>
<dd>
    @this.LclRes("String2")
</dd>

<h3>2. @Html.ActionLink(this.LclRes("How it works? (cartoon)"), "HowItWorksCartoon", "tutorial")</h3>

<h3>@this.LclRes("String3")</h3>
<h4>@this.LclRes("String4")</h4>
<dd>@this.LclRes("String5")</dd>

<h4>@this.LclRes("String6")</h4>
<dd>
    <li>@Html.ActionLink(this.LclRes("String7"), "whyUErrorToMeCartooon", "tutorial")</li>
    <li>@this.LclRes("String8")</li>
    <li>@this.LclRes("String9")</li>
    <li>@this.LclRes("String10")</li> @* kurwa jak to brzmi //TODO zmienić to *@
</dd>

<h4>@this.LclRes("String11")</h4>
<dd>
    <li>@this.LclRes("String12")</li>
    <li>@this.LclRes("String13")</li>
</dd>

<h3>s
@this.LclRes("String14")
</h3>

<h4>
    <dd>
        <li>@Html.ActionLink(this.LclRes("String15"), "friendlistTutorial", "Tutorial")</li>
        <li>@Html.ActionLink(this.LclRes("String16"), "createNewTransaction", "Tutorial")</li>
        <li>@Html.ActionLink(this.LclRes("String17"), "accAndExeTransactionTutorial", "Tutorial")</li>
        <li>@Html.ActionLink(this.LclRes("String18"), "suspendOptimization", "Tutorial")</li>
    </dd>
</h4>

Source/Views/Tutorial/accAndExeTransactionTutorial.cshtml
@{
    ViewBag.Title = "accAndExeTransactionTutorial";
}

<h2>@this.LclRes("Go back to") @Html.ActionLink(this.LclRes("tutorial menu"), "index", "tutorial")</h2>

<h3>@this.LclRes("String1")</h3>
<img src="@Url.Content(this.LclRes("Img1"))" alt="account and execute transaction pic"/>
<br />

<h3>@this.LclRes("String2")</h3>
<img src="@Url.Content(this.LclRes("Img2"))" alt="account and execute transaction pic"/>
<br />

<h3>@this.LclRes("String3")</h3>
<img src="@Url.Content(this.LclRes("Img3"))" alt="account and execute transaction pic"/>
<br />

<h3>@this.LclRes("String4")</h3>
<img src="@Url.Content(this.LclRes("Img4"))" alt="account and execute transaction pic"/>
<br />

<h3>@this.LclRes("String5")</h3>
<img src="@Url.Content(this.LclRes("Img5"))" alt="account and execute transaction pic"/>
<br />

<h3>@this.LclRes("String6")</h3>
<img src="@Url.Content(this.LclRes("Img6"))" alt="account and execute transaction pic"/>
<br />

Source/Views/Tutorial/createNewTransaction.cshtml
@{
    ViewBag.Title = "createNewTransactionTutorial";
}

<h2>@this.LclRes("Go back to") @Html.ActionLink(this.LclRes("tutorial menu"), "index", "tutorial")</h2>

<h3>@this.LclRes("String1")</h3>
<img src="@Url.Content(this.LclRes("Img1"))" alt="create new transaction tutorial pic"/>
<br />

<h3>@this.LclRes("String2")</h3>
<img src="@Url.Content(this.LclRes("Img2"))" alt="create new transaction tutorial pic"/>
<br />

<h3>@this.LclRes("String3")</h3>
<img src="@Url.Content(this.LclRes("Img3"))" alt="create new transaction tutorial pic"/>
<br />

<h3>@this.LclRes("String4")</h3>
<img src="@Url.Content(this.LclRes("Img4"))" alt="create new transaction tutorial pic"/>
<br />

<h3>@this.LclRes("String5")</h3>
<h3>@this.LclRes("String6")</h3>
<img src="@Url.Content(this.LclRes("Img5"))" alt="create new transaction tutorial pic"/>
<br />

Source/Views/Tutorial/friendlistTutorial.cshtml
@{
    ViewBag.Title = "friendlistTutorial";
}

<h2>@this.LclRes("Go back to") @Html.ActionLink(this.LclRes("tutorial menu"), "index", "tutorial")</h2>

<h3>@this.LclRes("String1")</h3>
<img src="@Url.Content(this.LclRes("Img1"))" alt="friends tutorial pic"/>
<br />

<h3>@this.LclRes("String2");</h3>
<img src="@Url.Content(this.LclRes("Img2"))" alt="friends tutorial pic"/> 
<br />

<h3>@this.LclRes("String3")</h3>
<img src="@Url.Content(this.LclRes("Img3"))" alt="friends tutorial pic"/> 
<br />

<h3>@this.LclRes("String4")</h3>
<img src="@Url.Content(this.LclRes("Img4"))" alt="friends tutorial pic"/> 

Source/Views/Tutorial/suspendOptimization.cshtml
@{
    ViewBag.Title = "suspendOptimization";
}

<h2>@this.LclRes("Go back to") @Html.ActionLink(this.LclRes("tutorial menu"), "index", "tutorial")</h2>

<h4>
    @this.LclRes("String1")
</h4>

<h4>
    @this.LclRes("String2")
</h4>

<h4>
    @this.LclRes("String3")
</h4>

<h4>
    @this.LclRes("String4")
</h4>

<h4>
    @this.LclRes("String5")
</h4>

Source/Views/Tutorial/whyUErrorToMeCartooon.cshtml
@{
    ViewBag.Title = "whyUErrorToMeCartooon";
}

<h2>@this.LclRes("Go back to") @Html.ActionLink(this.LclRes("tutorial menu"), "index", "tutorial")</h2>

<h4>@this.LclRes("String1")</h4>
<img src="@Url.Content(this.LclRes("Img1"))" alt="account and execute transaction pic"/>
<br /><br /><br />
<img src="@Url.Content(this.LclRes("Img2"))" alt="account and execute transaction pic"/>